# Generated by Django 5.1.2 on 2024-10-09 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('project_description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AddField(
            model_name='job',
            name='work_details',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='job_logos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('site', 'Site'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=10),
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
