# Generated by Django 5.0.1 on 2024-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
