# Generated by Django 5.0.1 on 2024-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_application_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
